### ISSUE TITLE
python injector fails with a bytes-like object is required

### ISSUE THREAD

**Issue by pmiess** [0install/0install#166]
running the 0compile gnu hello example on windows 10 64 with a 32 bit  python3 you get the following error

```
================= http://0install.net/tests/GNU-Hello.xml ==================

Selecting versions for GNU Hello...
Selection done.

Plan:

- GNU Hello: Compile 1.3 (sha1=2aae32fd27d194167eac7eb611d7ce0983f83dd7)
  - make: Use existing binary 3.81-3 (Windows-i486)
    - LibIconv: Use existing binary 1.9.2-1-3 (Windows-i486)
    - GetText: Use existing binary 0.14.4-3 (Windows-i486)
      - LibIconv: Use existing binary 1.9.2-1-3 (Windows-i486)

No dependencies need compiling... compile GNU Hello itself...

Traceback (most recent call last):
  File "C:\ProgramData\0install.net\implementations\sha256new_JVOJOX7AWISFZ6BGP46FTMBHTTRA2HP433NUG3VWEXGI3DC7INDA\0compile", line 77, in <module>
    matches[0](args[1:])
  File "C:\ProgramData\0install.net\implementations\sha256new_JVOJOX7AWISFZ6BGP46FTMBHTTRA2HP433NUG3VWEXGI3DC7INDA\autocompile.py", line 593, in do_autocompile
    compiler.build()
  File "C:\ProgramData\0install.net\implementations\sha256new_JVOJOX7AWISFZ6BGP46FTMBHTTRA2HP433NUG3VWEXGI3DC7INDA\autocompile.py", line 363, in build
    tasks.wait_for_blocker(self.recursive_build(self.iface_uri))
  File "C:\ProgramData\0install.net\implementations\sha256new_W63ETHPBDGDIEGHCLLZYU3MGWALIWOTVS4B5G6HSMTLSF36BOKFA\zeroinstall\support\tasks.py", line 517, in wait_for_blocker
    check(blocker)
  File "C:\ProgramData\0install.net\implementations\sha256new_W63ETHPBDGDIEGHCLLZYU3MGWALIWOTVS4B5G6HSMTLSF36BOKFA\zeroinstall\support\tasks.py", line 176, in check
    support.raise_with_traceback(ex[0], ex[1])
  File "C:\ProgramData\0install.net\implementations\sha256new_W63ETHPBDGDIEGHCLLZYU3MGWALIWOTVS4B5G6HSMTLSF36BOKFA\zeroinstall\support\__init__.py", line 104, in raise_with_traceback
    raise ex                                    # Python 3
  File "C:\ProgramData\0install.net\implementations\sha256new_W63ETHPBDGDIEGHCLLZYU3MGWALIWOTVS4B5G6HSMTLSF36BOKFA\zeroinstall\support\tasks.py", line 387, in _resume
    new_blockers = next(self.iterator)
  File "C:\ProgramData\0install.net\implementations\sha256new_JVOJOX7AWISFZ6BGP46FTMBHTTRA2HP433NUG3VWEXGI3DC7INDA\autocompile.py", line 321, in recursive_build
    tasks.check(build)
  File "C:\ProgramData\0install.net\implementations\sha256new_W63ETHPBDGDIEGHCLLZYU3MGWALIWOTVS4B5G6HSMTLSF36BOKFA\zeroinstall\support\tasks.py", line 176, in check
    support.raise_with_traceback(ex[0], ex[1])
  File "C:\ProgramData\0install.net\implementations\sha256new_W63ETHPBDGDIEGHCLLZYU3MGWALIWOTVS4B5G6HSMTLSF36BOKFA\zeroinstall\support\__init__.py", line 104, in raise_with_traceback
    raise ex                                    # Python 3
  File "C:\ProgramData\0install.net\implementations\sha256new_W63ETHPBDGDIEGHCLLZYU3MGWALIWOTVS4B5G6HSMTLSF36BOKFA\zeroinstall\support\tasks.py", line 387, in _resume
    new_blockers = next(self.iterator)
  File "C:\ProgramData\0install.net\implementations\sha256new_JVOJOX7AWISFZ6BGP46FTMBHTTRA2HP433NUG3VWEXGI3DC7INDA\autocompile.py", line 178, in compile_and_register
    tasks.check(download_missing)
  File "C:\ProgramData\0install.net\implementations\sha256new_W63ETHPBDGDIEGHCLLZYU3MGWALIWOTVS4B5G6HSMTLSF36BOKFA\zeroinstall\support\tasks.py", line 176, in check
    support.raise_with_traceback(ex[0], ex[1])
  File "C:\ProgramData\0install.net\implementations\sha256new_W63ETHPBDGDIEGHCLLZYU3MGWALIWOTVS4B5G6HSMTLSF36BOKFA\zeroinstall\support\__init__.py", line 104, in raise_with_traceback
    raise ex                                    # Python 3
  File "C:\ProgramData\0install.net\implementations\sha256new_W63ETHPBDGDIEGHCLLZYU3MGWALIWOTVS4B5G6HSMTLSF36BOKFA\zeroinstall\support\tasks.py", line 387, in _resume
    new_blockers = next(self.iterator)
  File "C:\ProgramData\0install.net\implementations\sha256new_W63ETHPBDGDIEGHCLLZYU3MGWALIWOTVS4B5G6HSMTLSF36BOKFA\zeroinstall\injector\selections.py", line 441, in download
    fetch_impls = config.fetcher.download_impls(needed_impls, stores)
  File "C:\ProgramData\0install.net\implementations\sha256new_W63ETHPBDGDIEGHCLLZYU3MGWALIWOTVS4B5G6HSMTLSF36BOKFA\zeroinstall\injector\fetch.py", line 642, in download_impls
    self._download_with_external_fetcher(implementations)
  File "C:\ProgramData\0install.net\implementations\sha256new_W63ETHPBDGDIEGHCLLZYU3MGWALIWOTVS4B5G6HSMTLSF36BOKFA\zeroinstall\injector\fetch.py", line 712, in _download_with_external_fetcher
    process.communicate(doc.toxml() + "\n")
  File "D:\obj\windows-release\37win32_Release\msi_python\zip_win32\subprocess.py", line 949, in communicate
  File "D:\obj\windows-release\37win32_Release\msi_python\zip_win32\subprocess.py", line 898, in _stdin_write
    TypeError: a bytes-like object is required, not 'str'
```

**Comment by bastianeicher** [comment]
Created a PR that should hopefully fix this.
