### ISSUE TITLE
support tar.zst in the 2.3 python version

### ISSUE THREAD

**Issue by pmiess** [0install/0install#173]
If you try to use 0watch to update a feed with a new tar.zst archive it fails to guess the archive type.
if you provide the archive type then zero install posts an error

```
0watch gmp.watch.py
downloading new db file
mingw-w64-x86_64-gmp-6.2.1-1-any.pkg.tar.zst has valid md5
mingw-w64-x86_64-gmp-6.2.1-1-any.pkg.tar.zst has valid sha256
mingw-w64-x86_64-gmp-6.2.1-1-any.pkg.tar.zst has valid pgp signature
downloading new db file
mingw-w64-i686-gmp-6.2.1-1-any.pkg.tar.zst has valid md5
mingw-w64-i686-gmp-6.2.1-1-any.pkg.tar.zst has valid sha256
mingw-w64-i686-gmp-6.2.1-1-any.pkg.tar.zst has valid pgp signature
Traceback (most recent call last):
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_UUKHJE54V5UDDL2EIMWO5PLH7R6OG7IHEWRPQMJVNPDN5CKRN4OA/zeroinstall/injector/fetch.py", line 449, in download_impl
    tasks.check(blocker)
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_UUKHJE54V5UDDL2EIMWO5PLH7R6OG7IHEWRPQMJVNPDN5CKRN4OA/zeroinstall/support/tasks.py", line 176, in check
    support.raise_with_traceback(ex[0], ex[1])
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_UUKHJE54V5UDDL2EIMWO5PLH7R6OG7IHEWRPQMJVNPDN5CKRN4OA/zeroinstall/support/__init__.py", line 104, in raise_with_traceback
    raise ex			                                # Python 3
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_UUKHJE54V5UDDL2EIMWO5PLH7R6OG7IHEWRPQMJVNPDN5CKRN4OA/zeroinstall/support/tasks.py", line 387, in _resume
    new_blockers = next(self.iterator)
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_UUKHJE54V5UDDL2EIMWO5PLH7R6OG7IHEWRPQMJVNPDN5CKRN4OA/zeroinstall/injector/fetch.py", line 141, in cook
    step.prepare(self, blockers)
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_UUKHJE54V5UDDL2EIMWO5PLH7R6OG7IHEWRPQMJVNPDN5CKRN4OA/zeroinstall/injector/fetch.py", line 818, in prepare
    self.blocker, self.stream = fetcher.download_archive(self.stepdata, impl_hint = self.impl_hint, may_use_mirror = self.may_use_mirror)
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_UUKHJE54V5UDDL2EIMWO5PLH7R6OG7IHEWRPQMJVNPDN5CKRN4OA/zeroinstall/injector/fetch.py", line 538, in download_archive
    unpack.check_type_ok(mime_type)
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_UUKHJE54V5UDDL2EIMWO5PLH7R6OG7IHEWRPQMJVNPDN5CKRN4OA/zeroinstall/zerostore/unpack.py", line 138, in check_type_ok
    raise SafeException(_("Unsupported archive type '%(type)s' (for injector version %(version)s)") % {'type': mime_type, 'version': version})
zeroinstall.SafeException: Unsupported archive type 'application/x-zstd-compressed-tar' (for injector version 2.3.12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_GHJMUQA4THAAAG62R4R55U2CLFGHNVIRH2TTBLKYH4SKBMZF7JPQ/0template.py", line 82, in <module>
    digest.add_digests(args.template, impl, config)
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_GHJMUQA4THAAAG62R4R55U2CLFGHNVIRH2TTBLKYH4SKBMZF7JPQ/digest.py", line 115, in add_digests
    tasks.wait_for_blocker(blocker)
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_UUKHJE54V5UDDL2EIMWO5PLH7R6OG7IHEWRPQMJVNPDN5CKRN4OA/zeroinstall/support/tasks.py", line 517, in wait_for_blocker
    check(blocker)
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_UUKHJE54V5UDDL2EIMWO5PLH7R6OG7IHEWRPQMJVNPDN5CKRN4OA/zeroinstall/support/tasks.py", line 176, in check
    support.raise_with_traceback(ex[0], ex[1])
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_UUKHJE54V5UDDL2EIMWO5PLH7R6OG7IHEWRPQMJVNPDN5CKRN4OA/zeroinstall/support/__init__.py", line 104, in raise_with_traceback
    raise ex			                                # Python 3
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_UUKHJE54V5UDDL2EIMWO5PLH7R6OG7IHEWRPQMJVNPDN5CKRN4OA/zeroinstall/support/tasks.py", line 387, in _resume
    new_blockers = next(self.iterator)
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_UUKHJE54V5UDDL2EIMWO5PLH7R6OG7IHEWRPQMJVNPDN5CKRN4OA/zeroinstall/injector/fetch.py", line 467, in download_impl
    ex = ex))
zeroinstall.SafeException: Error fetching /home/pmiess/projects/my.apps.0install.net/lib/gmp.xml.template 0: Unsupported archive type 'application/x-zstd-compressed-tar' (for injector version 2.3.12)
```

**Comment by FiyaasAhmedKhan** [comment]
> [#၁၇၃](https://github.com/0install/0install/issues/173)
