### ISSUE TITLE
Cannot install any packages on Manjaro

### ISSUE THREAD

**Issue by ygarl** [0install/0install#82]
Attempting to install any packages (even ones I know should work) fail to:
"WARNING:0install:invalid literal for int() with base 10: '-'"
Here's a run with option -vvc...
`<~/0install-linux-x86_64-2.12.1 >>> 0launch -vvc http://0install.de/feeds/ZeroInstall_Tools.xml                                                                   [1]
INFO:root:Running 0launch 2.0 ['http://0install.de/feeds/ZeroInstall_Tools.xml']; Python 3.6.5 (default, May 11 2018, 04:00:52) 
[GCC 8.1.0]
INFO:0install:Loading configuration from /home/bobsal/.config/0install.net/injector/global
DEBUG:0install:Supported systems: '{'Linux': 1, 'POSIX': 2, None: 3}'
DEBUG:0install:Supported processors: '{'x86_64': 0, 'i686': 1, 'i586': 2, 'i486': 3, 'i386': 4, None: 5}'
DEBUG:0install:Initialising new interface object for http://0install.de/feeds/ZeroInstall_Tools.xml
DEBUG:0install:Processing feed http://0install.de/feeds/ZeroInstall_Tools.xml
INFO:0install:No run <command> in http://0install.de/feeds/ZeroInstall_Tools.xml
DEBUG:0install:Processing feed http://0install.de/feeds/ZeroInstall_Tools.xml
INFO:0install:No run <command> in http://0install.de/feeds/ZeroInstall_Tools.xml
INFO:0install:Scheduling new task: solve_and_download_impls
INFO:0install:Scheduling new task: quitter
DEBUG:0install:Entering mainloop, waiting for solve_and_download_impls
INFO:0install:Task 'quitter' stopping and waiting for '(<Blocker:solve_and_download_impls>,)'
INFO:0install:Scheduling new task: solve_with_downloads
INFO:0install:Task 'solve_and_download_impls' stopping and waiting for '(<Blocker:solve_with_downloads>,)'
DEBUG:0install:Processing feed http://0install.de/feeds/ZeroInstall_Tools.xml
INFO:0install:No run <command> in http://0install.de/feeds/ZeroInstall_Tools.xml
DEBUG:0install:Processing feed http://0install.de/feeds/ZeroInstall_Tools.xml
INFO:0install:No run <command> in http://0install.de/feeds/ZeroInstall_Tools.xml
DEBUG:0install:download_and_import_feed http://0install.de/feeds/ZeroInstall_Tools.xml
[http://0install.de/feeds/ZeroInstall_Tools.xml] INFO:0install:Scheduling new task: download_done_stats
INFO:0install:Scheduling new task: download
INFO:0install:Scheduling new task: fetch_feed http://0install.de/feeds/ZeroInstall_Tools.xml
INFO:0install:Scheduling new task: monitor feed downloads for http://0install.de/feeds/ZeroInstall_Tools.xml
INFO:0install:Task 'solve_with_downloads' stopping and waiting for 'dict_values([<Blocker:monitor feed downloads for http://0install.de/feeds/ZeroInstall_Tools.xml>])'
INFO:0install:Task 'fetch_feed http://0install.de/feeds/ZeroInstall_Tools.xml' stopping and waiting for '(<Blocker:download>,)'
INFO:0install:Task 'monitor feed downloads for http://0install.de/feeds/ZeroInstall_Tools.xml' stopping and waiting for '(<Blocker:fetch_feed http://0install.de/feeds/ZeroInstall_Tools.xml>, <Blocker:Mirror timeout>)'
INFO:0install:Task 'download_done_stats' stopping and waiting for '(<Blocker:download>,)'
INFO:0install:Scheduling new task: download
INFO:0install:Task 'download' stopping and waiting for '(<Blocker:download>,)'
INFO:0install:Task 'download' stopping and waiting for '(<Blocker:wait for thread http://0install.de/feeds/ZeroInstall_Tools.xml>, <Blocker:abort http://0install.de/feeds/ZeroInstall_Tools.xml>)'
[http://0install.de/feeds/ZeroInstall_Tools.xml] INFO:0install:Running {Task(download)} due to triggering of 'wait for thread http://0install.de/feeds/ZeroInstall_Tools.xml'
INFO:0install:Running {Task(download)} due to triggering of 'download'
INFO:0install:Running {Task(download_done_stats), Task(fetch_feed http://0install.de/feeds/ZeroInstall_Tools.xml)} due to triggering of 'download'
INFO:0install:Scheduling new task: download keys for http://0install.de/feeds/ZeroInstall_Tools.xml
INFO:0install:Task 'fetch_feed http://0install.de/feeds/ZeroInstall_Tools.xml' stopping and waiting for '(<Blocker:download keys for http://0install.de/feeds/ZeroInstall_Tools.xml>,)'
INFO:0install:Running download_done_stats
INFO:0install:Exception from 'download keys for http://0install.de/feeds/ZeroInstall_Tools.xml': invalid literal for int() with base 10: '-'
DEBUG:0install:Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/tasks.py", line 254, in _resume
    new_blockers = next(self.iterator)
  File "/usr/lib/python3.6/site-packages/zeroinstall/injector/iface_cache.py", line 91, in download_keys
    key_id = x.need_key()
  File "/usr/lib/python3.6/site-packages/zeroinstall/injector/gpg.py", line 111, in need_key
    rc = int(self.status[self.RC])
ValueError: invalid literal for int() with base 10: '-'

INFO:0install:Running {Task(fetch_feed http://0install.de/feeds/ZeroInstall_Tools.xml)} due to triggering of 'download keys for http://0install.de/feeds/ZeroInstall_Tools.xml'
INFO:0install:Exception from 'fetch_feed http://0install.de/feeds/ZeroInstall_Tools.xml': invalid literal for int() with base 10: '-'
DEBUG:0install:Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/tasks.py", line 254, in _resume
    new_blockers = next(self.iterator)
  File "/usr/lib/python3.6/site-packages/zeroinstall/injector/fetch.py", line 334, in fetch_feed
    tasks.check(keys_downloaded.finished)
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/tasks.py", line 66, in check
    support.raise_with_traceback(ex[0], ex[1])
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/__init__.py", line 95, in raise_with_traceback
    raise ex                                    # Python 3
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/tasks.py", line 254, in _resume
    new_blockers = next(self.iterator)
  File "/usr/lib/python3.6/site-packages/zeroinstall/injector/iface_cache.py", line 91, in download_keys
    key_id = x.need_key()
  File "/usr/lib/python3.6/site-packages/zeroinstall/injector/gpg.py", line 111, in need_key
    rc = int(self.status[self.RC])
ValueError: invalid literal for int() with base 10: '-'

INFO:0install:Running {Task(monitor feed downloads for http://0install.de/feeds/ZeroInstall_Tools.xml)} due to triggering of 'fetch_feed http://0install.de/feeds/ZeroInstall_Tools.xml'
INFO:0install:Exception from 'monitor feed downloads for http://0install.de/feeds/ZeroInstall_Tools.xml': invalid literal for int() with base 10: '-'
DEBUG:0install:Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/tasks.py", line 254, in _resume
    new_blockers = next(self.iterator)
  File "/usr/lib/python3.6/site-packages/zeroinstall/injector/fetch.py", line 239, in wait_for_downloads
    tasks.check(primary)
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/tasks.py", line 66, in check
    support.raise_with_traceback(ex[0], ex[1])
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/__init__.py", line 95, in raise_with_traceback
    raise ex                                    # Python 3
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/tasks.py", line 254, in _resume
    new_blockers = next(self.iterator)
  File "/usr/lib/python3.6/site-packages/zeroinstall/injector/fetch.py", line 334, in fetch_feed
    tasks.check(keys_downloaded.finished)
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/tasks.py", line 66, in check
    support.raise_with_traceback(ex[0], ex[1])
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/__init__.py", line 95, in raise_with_traceback
    raise ex                                    # Python 3
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/tasks.py", line 254, in _resume
    new_blockers = next(self.iterator)
  File "/usr/lib/python3.6/site-packages/zeroinstall/injector/iface_cache.py", line 91, in download_keys
    key_id = x.need_key()
  File "/usr/lib/python3.6/site-packages/zeroinstall/injector/gpg.py", line 111, in need_key
    rc = int(self.status[self.RC])
ValueError: invalid literal for int() with base 10: '-'

INFO:0install:Running {Task(solve_with_downloads)} due to triggering of 'monitor feed downloads for http://0install.de/feeds/ZeroInstall_Tools.xml'
WARNING:0install:invalid literal for int() with base 10: '-'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/tasks.py", line 254, in _resume
    new_blockers = next(self.iterator)
  File "/usr/lib/python3.6/site-packages/zeroinstall/injector/fetch.py", line 239, in wait_for_downloads
    tasks.check(primary)
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/tasks.py", line 66, in check
    support.raise_with_traceback(ex[0], ex[1])
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/__init__.py", line 95, in raise_with_traceback
    raise ex                                    # Python 3
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/tasks.py", line 254, in _resume
    new_blockers = next(self.iterator)
  File "/usr/lib/python3.6/site-packages/zeroinstall/injector/fetch.py", line 334, in fetch_feed
    tasks.check(keys_downloaded.finished)
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/tasks.py", line 66, in check
    support.raise_with_traceback(ex[0], ex[1])
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/__init__.py", line 95, in raise_with_traceback
    raise ex                                    # Python 3
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/tasks.py", line 254, in _resume
    new_blockers = next(self.iterator)
  File "/usr/lib/python3.6/site-packages/zeroinstall/injector/iface_cache.py", line 91, in download_keys
    key_id = x.need_key()
  File "/usr/lib/python3.6/site-packages/zeroinstall/injector/gpg.py", line 111, in need_key
    rc = int(self.status[self.RC])
NoneType: None
DEBUG:0install:Processing feed http://0install.de/feeds/ZeroInstall_Tools.xml
INFO:0install:No run <command> in http://0install.de/feeds/ZeroInstall_Tools.xml
DEBUG:0install:Processing feed http://0install.de/feeds/ZeroInstall_Tools.xml
INFO:0install:No run <command> in http://0install.de/feeds/ZeroInstall_Tools.xml
INFO:0install:Running {Task(solve_and_download_impls)} due to triggering of 'solve_with_downloads'
INFO:0install:Exception from 'solve_and_download_impls': Can't find all required implementations:
- http://0install.de/feeds/ZeroInstall_Tools.xml -> (problem)
    No known implementations at all
DEBUG:0install:Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/tasks.py", line 254, in _resume
    new_blockers = next(self.iterator)
  File "/usr/lib/python3.6/site-packages/zeroinstall/injector/driver.py", line 158, in solve_and_download_impls
    raise self.solver.get_failure_reason()
zeroinstall.SafeException: Can't find all required implementations:
- http://0install.de/feeds/ZeroInstall_Tools.xml -> (problem)
    No known implementations at all

INFO:0install:Running {Task(quitter)} due to triggering of 'solve_and_download_impls'
Traceback (most recent call last):
  File "/bin/0launch", line 14, in <module>
    cli.main(sys.argv[1:])
  File "/usr/lib/python3.6/site-packages/zeroinstall/injector/cli.py", line 143, in main
    run.handle(config, options, args)
  File "/usr/lib/python3.6/site-packages/zeroinstall/cmd/run.py", line 48, in handle
    test_callback = test_callback)
  File "/usr/lib/python3.6/site-packages/zeroinstall/cmd/select.py", line 73, in get_selections
    return get_selections_for(requirements, config, options, select_only, download_only, test_callback)
  File "/usr/lib/python3.6/site-packages/zeroinstall/cmd/select.py", line 154, in get_selections_for
    tasks.wait_for_blocker(downloaded)
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/tasks.py", line 373, in wait_for_blocker
    check(blocker)
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/tasks.py", line 66, in check
    support.raise_with_traceback(ex[0], ex[1])
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/__init__.py", line 95, in raise_with_traceback
    raise ex                                    # Python 3
  File "/usr/lib/python3.6/site-packages/zeroinstall/support/tasks.py", line 254, in _resume
    new_blockers = next(self.iterator)
  File "/usr/lib/python3.6/site-packages/zeroinstall/injector/driver.py", line 158, in solve_and_download_impls
    raise self.solver.get_failure_reason()
zeroinstall.SafeException: Can't find all required implementations:
- http://0install.de/feeds/ZeroInstall_Tools.xml -> (problem)
    No known implementations at all>'

I've no clue why, or how to fix this however...

**Comment by talex5** [comment]
0install 2.0 is from 2013. It seems to work with a newer version (well, mono crashes, but I guess that's a different problem):

```
$ docker run --rm -it jonathonf/manjaro  bash
# pacman -S mono tar gzip
[ install according to http://0install.net/install-linux.html#arch ]
# 0launch -cv http://0install.de/feeds/ZeroInstall_Tools.xml
0launch: /usr/lib/libcurl.so.3: no version information available (required by 0launch)
info: 0install 2.12.1 (OCaml version): verbose mode on
info: Getting new selections for http://0install.de/feeds/ZeroInstall_Tools.xml
info: Ignoring invalid distribution package name 'app-crypt/gnupg'
info: exec /usr/bin/mono /var/cache/0install.net/implementations/sha256new_RYIPUIAPNYL3W5BXPNGVFLUF4HIMU343HZ4LFRCQUZYM56CP3PFA/0publish-win.exe
*** stack smashing detected ***: <unknown> terminated
```

**Comment by talex5** [comment]
Closing; please reopen if it still happens with a recent version.
